// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ScreenResolution","status":false,"description":"ゲームスクリーンの解像度を好きなように変更することができます","parameters":{"Screen Width":"612","Screen Height":"468"}},
{"name":"DP_ZoomController","status":true,"description":"マップの拡大率を制御します。v0.31 beta20160116","parameters":{"Base Scale":"0.75","Encount Effect":"true"}},
{"name":"MessageWindowHidden","status":true,"description":"メッセージウィンドウ一時消去プラグイン","parameters":{"ボタン名称":"shift"}},
{"name":"UTA_MessageSkip","status":true,"description":"特定キーを押す事でメッセージをスキップできるようにします。","parameters":{"Skip Key":"control","Show Trace":"false"}},
{"name":"Single_Actor","status":true,"description":"One-Actor's menu. This plugin is made for one playable actor only.","parameters":{}},
{"name":"AKUNOU_MapScrollDisable","status":false,"description":"プレイヤーキャラの移動に同期した画面スクロールを、一時的に無効にするプラグインコマンドを追加します。","parameters":{}},
{"name":"OrangeMapshot","status":false,"description":"This plugin will save a picture of the entire map on a Mapshots folder when you press a key. <OrangeMapshot>","parameters":{"useMapName":"true","layerType":"0","drawAutoShadows":"true","drawEvents":"true","keyCode":"44","imageType":"png","imageQuality":"70","imagePath":"./Mapshots"}},
{"name":"TMMoveEx","status":false,"description":"壁衝突音やリージョンによる通行設定などの機能を追加します。","parameters":{"passableRegionId":"251","dontPassRegionId":"252","seKnockWall":"<name:Blow1><volume:90><pitch:100>","knockWallPan":"75","knockWallInterval":"30","turnKeyCode":"83","movableRegion1":"","movableRegion2":"","movableRegion3":"","movableRegion4":"","movableRegion5":"","movableRegion6":"","movableRegion7":"","movableRegion8":"","movableRegion9":"","movableRegion10":""}},
{"name":"ParallaxesNonBlur","status":false,"description":"視差ゼロ遠景のぼかし除去プラグイン","parameters":{}},
{"name":"CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン</span></td>\n</tr>\n<tr>\n<td id=\"L78\" class=\"blob-num js-line-number\" data-line-number=\"78\"></td>\n<td id=\"LC78\" class=\"blob-code blob-code-inner js-file-line\"><span class=\"pl-c\"> *","parameters":{"常時ダッシュ</span></td>":"ON</span></td>","コマンド記憶</span></td>":"OFF</span></td>","BGM音量</span></td>":"40</span></td>","BGS音量</span></td>":"40</span></td>","ME音量</span></td>":"40</span></td>","SE音量</span></td>":"40</span></td>","常時ダッシュ消去</span></td>":"OFF</span></td>","コマンド記憶消去</span></td>":"OFF</span></td>","BGM音量消去</span></td>":"OFF</span></td>","BGS音量消去</span></td>":"OFF</span></td>","ME音量消去</span></td>":"OFF</span></td>","SE音量消去</span></td>":"OFF</span></td>"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"logo","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}}
];
